neo4j:
    password: ENC[AES256_GCM,data:4PqNqQ/By6EVbQkPE+W6nyfj8xtyNDG/213XP3N8L7c=,iv:SQsCf4j12CnHjPz1E+1JBwIUOnCszblpErO23vdiV4M=,tag:lYmrkhRgWkOVkI7JIHep8A==,type:str]
apollo:
    apiKey: ENC[AES256_GCM,data:3ABZrNiZ4B5QTc8gZom0f0loGZkFlNxGhXHIWx9FJ5c=,iv:2BtE3NNDb10JM88OjS8hKN76Idme/g+4OHyDl65ghFs=,tag:5hLIX5dCpx+Oww9wvrzBeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13da407hamk8c3rdp3nu3q8hqgxsefn902vrxsuphw2ljfmd2k5qqy7mgzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWG1ZSHVBamhWSUgzbHFB
            NWp2Y210V3pqSFlPNzlnVVhCWFIyWTl4YjNBCk44VThPcUhMSHMyMmo2ZENDNnU2
            Y3FVLzdmTW9yWE1vNFlnSEVPd0NiWWsKLS0tIDZJUzI2MUNDYm8zT3c3Z1l2Rnlz
            S3BhMG9RdnZMbGE5WHR2bml4MGVCemMKnnga0cUzcIK/yG9SBoHRz1mpcSkAhpci
            qgGRQagnvOlWXun5UjZdt3rM9f3Bv9gXV4MOJhb7EGKuXMJMFK/+6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRkNGcWhtcFNFRFBtZ2ph
            TWtRZm5JVHZWcnFMdXV1Mmh4N1Qva2NuWEZ3CmxBNkM0Y1Zwd0Z6YmlqYno1TXA3
            NndpVHdzTnNTc3JSaUZMeklkaDN2bXcKLS0tIE5Gak8vYnptMm83QVBLa3BUUEds
            S0dkZjhQazNiUWMralVuMmh2cWdOQ2cKY/lMDyyTImpIgZx5irQf1BsypPbS9Nuj
            WKF1WlGA4lKzs7weUYX6JYW9JR/TD9dIS/qrYL9yc2GQUr/Cpm6MSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdkJtMzkrQmhGcWlHaGsr
            Y3gwUlpaL3ZIR2VFVktxSXlWWlBGVm1YWmpnClJrS2pPUWcyVmMybnhmUlhxVE9u
            eWQza2xDRFprd04rdUQ4OGtqTmVsVncKLS0tIFZhTklIdHVtYjFnMk16VGJjek9j
            Y0hNVE9yMGt0SXNrOVYxaFo5QUdZbUkKidn6tW8uoZJ9gRUeUF/IF5Qqx3HG+46V
            6Q7ycFS1GFXHG4tPJzLE5LkK/jDp3YfhUPfFg9uVJ7Y/5je5a41LTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpLzJtSE1zdWhzYXJ3Mnht
            WGdlR01ZaERubXJtTVZhYWtUVTcyMDNSVGlvCkhoZFlWNUVxNC9ueUwxZ05QZGNX
            dEg2TXJXd05leHFFVEp2T0xLV2dmYmcKLS0tIE55RTlSRzA3VWZTUTVrajJDeFJH
            SXdCRnNVdHRBU3E4MDVzSCt3aVBmVTAKQxAcbKXS80WiUEks4B3EytDozZycvQan
            2/Y/jDC0kUvSnwWB3A22nWyu+JqLBvFbS0bemZ7pKkuU1NulSphKsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T16:35:58Z"
    mac: ENC[AES256_GCM,data:+gMDgCfoDPmrQnO8OCEGjJvD1ZFD96U+NgUMUAXQqtEuexYkUZ9MPF9D1jdVsIkm5VHNOCDof6SE3O7xkz2sv86H/Qfml/0qslPYltxk9kgvgXEBcpphHFq+V4P8CKexWsw6XanTX4PoM41QhXcBIhmllyz8d+1zIyNp7GPpJpE=,iv:s4Gk2/X7I6ZYAkdQsgjoltavN+S9jEQESW7p8fmQlvo=,tag:pcRNi4ELXil6ebfIYHrrtQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
