---
{{- if .Values.harvester.ui.enabled }}
{{- $configGenerator := dict
"config" .Values.harvester.ui.config
"root" $
"commonLabels" .Values.harvester.ui.commonLabels
"name" (tpl .Values.harvester.ui.fullName .) }}

{{- include "common.config.resources" $configGenerator}}
{{- end }}
