---
{{- if .Values.neo4j.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ tpl .Values.neo4j.fullName $ }}
  labels:
    {{- (tpl ($.Values.neo4j.commonLabels | toYaml ) $) | nindent 4 }}
spec:
  serviceName: {{ tpl .Values.neo4j.fullName $ }}
  replicas: 1
  selector:
    matchLabels:
      {{- (tpl ($.Values.neo4j.commonLabels | toYaml ) $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- (tpl ($.Values.neo4j.commonLabels | toYaml ) $) | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/neo4j/config.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- include "common.security.podSecurityContext.restricted" dict | nindent 8 }}
      containers:
      - name: neo4j
      {{- with $.Values.neo4j.image }}
        image: {{ tpl (printf "%s:%s" .repository .tag) $ }}
      {{- end }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.neo4j.httpPort }}
            name: http
          - containerPort: {{ .Values.neo4j.boltPort }}
            name: bolt
        envFrom:
        - configMapRef:
            name: {{ tpl .Values.neo4j.fullName $ }}
        - secretRef:
            name: {{ tpl .Values.neo4j.fullName $ }}
        securityContext:
          {{- include "common.security.containerSecurityContext.restricted" dict | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/neo4j/data
          name: neo4j-data
  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-csi-lrs-projects
      resources:
        requests:
          storage: 2Gi
{{- end }}
