---
{{- if .Values.harvester.worker.enabled }}
{{- $configGenerator := dict
"config" .Values.harvester.worker.config
"root" $
"commonLabels" .Values.harvester.worker.commonLabels
"name" (tpl .Values.harvester.worker.fullName .) }}

{{- include "common.config.resources" $configGenerator}}
{{- end }}
