---
{{- if .Values.apollo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.apollo.fullName $ }}
  labels:
    {{- (tpl ($.Values.apollo.commonLabels | toYaml ) $) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- (tpl ($.Values.apollo.commonLabels | toYaml ) $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- (tpl ($.Values.apollo.commonLabels | toYaml ) $) | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/apollo/config.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- include "common.security.podSecurityContext.restricted" dict | nindent 8 }}

      containers:
      - name: apollo
      {{- with $.Values.apollo.image }}
        image: {{ tpl (printf "%s:%s" .repository .tag) $ }}
      {{- end }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.apollo.httpPort }}
            name: http
        envFrom:
        - configMapRef:
            name: {{ tpl .Values.apollo.fullName $ }}
        - secretRef:
            name: {{ tpl .Values.apollo.fullName $ }}
        securityContext:
          {{- include "common.security.containerSecurityContext.restricted" dict | nindent 10 }}
{{- end }}
