---
{{- if .Values.apollo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.apollo.fullName $ }}
  labels:
    {{- (tpl ($.Values.apollo.commonLabels | toYaml ) $) | nindent 4 }}

spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.apollo.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- (tpl ($.Values.apollo.commonLabels | toYaml ) $) | nindent 4 }}
{{- end }}
