---
{{- if .Values.crisalidBus.enabled }}
{{- $configGenerator := dict
"config" .Values.crisalidBus.config
"root" $
"commonLabels" .Values.crisalidBus.commonLabels
"name" (tpl .Values.crisalidBus.fullName .) }}

{{- include "common.config.resources" $configGenerator}}
{{- end }}
