---
{{- if .Values.crisalidBus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.crisalidBus.fullName $ }}
  labels:
    {{- (tpl ($.Values.crisalidBus.commonLabels | toYaml ) $) | nindent 4 }}

spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.crisalidBus.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.crisalidBus.amqPort }}
      targetPort: amq
      protocol: TCP
      name: amq
  selector:
    {{- (tpl ($.Values.crisalidBus.commonLabels | toYaml ) $) | nindent 4 }}
{{- end }}
